# docker-compose.yml
version: "2"

services:
  mockbank:
    build:
      context: .
      dockerfile: Dockerfile.MockBank
    ports:
      - "5002:80"
  gateway:
    environment:
      MockBankApiUrl: "http://mockbank/"
    build:
      context: .
      dockerfile: Dockerfile.Gateway
    depends_on:
      - mockbank
    ports:
      - "5001:80"
