name: $(Version.Major).$(Version.Minor).$(Version.Patch)

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  Version.Major: 0
  Version.Minor: 0
  Version.Patch: $[counter(variables['Version.Minor'], 0)]

steps:
  - task: Docker@2
    displayName: "build gateway image"
    inputs:
      command: "build"
      Dockerfile: "src/Checkout.Gateway.API/Dockerfile"
      tags: |
        $(Build.BuildNumber)
        $(Build.SourceBranchName)
        $(Build.SourceBranchName)-$(Build.BuildNumber)
  - task: Docker@2
    displayName: "build mock api image"
    inputs:
      command: "build"
      Dockerfile: "tools/MockBank.API/Dockerfile"
      tags: |
        $(Build.BuildNumber)
        $(Build.SourceBranchName)
        $(Build.SourceBranchName)-$(Build.BuildNumber)
